Refactor for inbound transfer
openMF/ph-ee-connector-ams-paygops pull request #22
Opened 2023-03-03 12:37 UTC by truthfool

## Description

- Refactor for inbound transfer

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-03-03 12:37 UTC, truthfool commented
@avikganguly01 @fynmanoj

2023-03-09 06:58 UTC, fynmanoj requested changes

2023-03-09 06:58 UTC, fynmanoj commented on src/main/java/org/mifos/connector/ams/paygops/camel/route/PaygopsRouteBuilder.java
> +                    logger.info("Body : {}",body);
use log level debug here

2023-03-09 06:58 UTC, fynmanoj commented on src/main/java/org/mifos/connector/ams/paygops/camel/route/PaygopsRouteBuilder.java
>                          logger.info("Validation request DTO: \n\n\n" + paygopsRequestDTO);
use debug level logs

2023-03-09 06:58 UTC, fynmanoj commented on src/main/java/org/mifos/connector/ams/paygops/camel/route/PaygopsRouteBuilder.java
> +                            exchange.setProperty("msisdn", result.getWallet_msisdn().substring(1));
Why are we doing this substring without any condition check. look for the character you are trying to remove.

2023-03-21 06:17 UTC, fynmanoj requested changes
Clarification required

2023-03-21 06:17 UTC, fynmanoj commented on src/main/java/org/mifos/connector/ams/paygops/camel/route/PaygopsRouteBuilder.java
> +                            exchange.setProperty("accountHoldingInstitutionId", exchange.getProperty("accountHoldingInstitutionId"));
why do we need accountHoldingInstitutionId in paygops?

2023-03-22 11:22 UTC, merged